name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Safely use secret as environment variable
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "Secret loaded into environment"
