name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret template
        run: echo "The secret is \${{ secrets.SECRET }}"
      - name: Use secret safely
        env:
          MY_TOKEN: ${{ secrets.SECRET }}
        run: echo "Using secret in an API call (not printed)"
