name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Safely use secret
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          [ -n "$SECRET" ]

      - name: Print escaped secret reference
        run: echo "The secret is \${{ secrets.SECRET }}"
