name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret safely (masked)
        run: echo "Using secret ${{ secrets.SECRET }}"

      - name: Print escaped secret reference
        run: echo "The secret is \${{ secrets.SECRET }}"
