name: secret-workflow

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        env:
          SECRET: ${{ secrets.SECRET }}
        run: echo "Using secret $SECRET"

      - name: Print escaped secret reference
        run: echo "The secret is \${{ secrets.SECRET }}"
